[package]
name = "actix-api"
version = "0.1.0"
authors = ["Ron Alonzo <alonzo.ronald@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3.3.2"
dotenv = "0.15"
rust_gpiozero = "0.2"

